import Head from "next/head";
import styles from "@/styles/Home.module.css";
import React from "react";
import Link from "next/link";
import { Canvas } from "@react-three/fiber";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>my-own-vocabulary</p>
        <Canvas>
          <mesh>
            <boxGeometry />
            <meshNormalMaterial />
          </mesh>
        </Canvas>
        <Link href="/vocabulary/list?page=1">Start!</Link>
      </main>
    </>
  );
}
